spring:
#  thymeleaf:
#    cache: false
#    prefix: file:src/main/resources/templates/
  application.name: taxtracker
  datasource:
    url: jdbc:postgresql://localhost:5432/taxtracker
    username: taxtracker
    password: taxtracker
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

tax:
  currencyBeacon:
    baseUrl: https://api.currencybeacon.com/v1
    apiKey: ${CURRENCYBEACON_API_KEY:}
    enabled: ${CURRENCYBEACON_ENABLED:false}
  skipPaidFor:
    - 202411
    - 202504
